---
title: "エディタ制(仮称)について"
author: "成果検討分科会 伊藤成朗"
date: last-modified
date-format: "MMMM DD, YYYY, HH:MM ZZ"
execute:
  echo: false
engine: knitr
pdf-engine: lualatex
format:
  html:
    standalone: true
    embed-resources: true
    toc: true
    toc-location: left
    grid:
      margin-width: 350px
####  pdf: default
  docx: default
callout-appearance: simple
callout-icon: false
bibliography: ../../../../seiro.bib
link-citations: true
reference-location: margin
citation-location: margin
#### # quarto render AboutEditor.qmd
#### c:\seiro\languages\R\R-4.4.1\bin\x64\Rscript.exe -e "path <- 'c:/seiro/docs/personal/Miscelleneous/testrepo/posts/AboutEditor/'; rmarkdown::render(paste0(path, 'AboutEditor.Rmd'), output_format = 'all')"
---
```{css CSS setting, echo=FALSE, results = "hide"}
.SeiroBenign {
  background-color: #FFEBCD;
  padding: 0.5em; /*文字まわり（上下左右）の余白*/
  /* border: 1px solid yellow; */
  /* font-weight: bold; */
}
.SeiroLightGreen {
  background-color: #D0F0C0; /* Tea green */
  padding: 0.5em; /*文字まわり（上下左右）の余白*/
  font-family: Noto S	ans;
  /* border: 1px solid yellow; */
  /* font-weight: bold; */
}
/* Define a margin before hX (header level X) element */
h1  {
  margin-top: 3ex;
  margin-bottom: 3ex;
  /* background: #c2edff; */ /*背景色*/
  padding: 0.5em;/*文字まわり（上下左右）の余白*/
}
h2  {
  margin-top: 2ex;
  margin-bottom: 2ex;
  padding: 0.5em;/*文字周りの余白*/
  color: #010101;/*文字色*/
  /* background: #eaf3ff; */ /*背景色*/
  /* border-bottom: solid 3px #516ab6; */ /*下線*/
}
```

<style type="text/css">
  body, td{
  font-size: 16pt;
}
</style>


::: {.callout-important title='成果検討過程の役割' collapse='true'}
質の高い研究成果のみを年度内に出版すること
:::

# 役割

1. スケジュール管理
1. 対話の齟齬を減らす

# 目的

1. 年度内出版を実現すること
1. 成果の質や完成度を高めること
   a) **対話齟齬による時間損失を減らし、成果改善の時間を増やす**こと
   a) 校正担当者の負担を減らすこと

# 背景・動機

担当者不在の体制

* 座長が担当者
   * 多岐にわたる内容と多くの分量: 座長の能力を超える
   * 検討過程の生産性? 
   * 座長が替わると監理基準も(時間を通じた公平性)?
* 全員が全部を把握
   * 意識が散漫
   * 大過ないものは手分け
   * 課題ありを全員で考える 

# エディタ(仮称)とは

## エディタがすべきこと



1. 検討者指摘と研究会対応の完・未了チェック
1. 研検間対話の円滑化、意見不一致のまとめ、検討者指摘と研究会対応の正当性監視、分科会への報告

::: {.callout-note title='対話を円滑にするためにエディタができること' collapse='true'}
* 明確化: 検討者の指摘事項、著者の修正事項、何をどのように変更すべきか/したか、なぜか
* 履歴の維持: 原則的に追加の指摘を認めない、(指摘対応以外も含め)論旨に関わる内容修正を明記させる
* 検討過程での表現の穏当さも「編集」
   * [事故によって自分の名前で公開されたときにも困らない表現や論調を堅持](https://macartan.github.io/teaching/how-to-critique#pointers)
:::
::: {.callout-note title='正当性監視' collapse='true'}
* 考察対象の尊重: 検討者は「XではなくYを問うべきでは」など、新たな問いを立てることを要求してはいけない、提示された考察に応えるべき
* 採否の論拠
   * 新奇性
   * 証拠や議論の質
   * 社会への貢献
   * 検討者の「学派」(意見・見方)との一致で決めない
* 相互に矛盾する結果の消去
:::

3. 事務局への検討完了日変更の相談
4. オプショナル: 検討者2名指摘の簡潔なまとめ(大きな項目提示のみ)

::: {.callout-note title='まとめ例' collapse="true"}
   * 例1
      1. 推計において効果多様性を検討すること 
      1. 母集団を明示し外的妥当性を議論すること
      1. 欠落変数を考慮したplacebo testを検討すること
      1. (以下略)
   * 例2
      1. 総論での枠組み提示が欠けていること 
      1. 一部章(3、5章)での完成度を高めること
      1. (以下略)
   * 「まとめ」ならば検討者に求める方が良いかも?&larr;今回は時すでに遅し^[新年度の成果検討体制は前年度2月中(第1稿提出時)に組む方が望ましい ]
   * 「まとめ」を積み重ねると内部出版物に求められる条件が明らかになっていくかも?
:::

## エディタがすべきではないこと

* 成果検討そのもの、出版可否の判断^[ジャーナル・エディタとの最大の相違点 ]
   * エディタは検討者を代替しない^[成果検討分科会委員(研究企画委員)としてコメント・質問をすることは可 ]
   * それとも、第3査読者が必要になったときのみ許容するか=エディタが第3査読者になる^[分科会委員として伊藤が第3査読者になった経験あり(座長、企画課長からの依頼) ]
* 研検間の意見不一致の強引な解消
   * 不一致は成果公開後に議論しても良い
   * 成果を歪めてしまう可能性、分科会に諮る方が安全


