---
title: |
  Fighting for growth\
  Labour scarcity and technological progress during the British Industrial Revolution\
  *American Economic Review* \
  [2026 (forthcoming)](https://www.aeaweb.org/articles/pdf/doi/10.1257/aer.20240393)
author: "伊藤成朗"
date: last-modified
date-format: "MMMM DD, YYYY, HH:MM ZZ"
execute:
  echo: false
engine: knitr
pdf-engine: lualatex
#### number-sections: true #### needed for cross ref the sections with @sec-Tag
format:
  html:
    standalone: true
    embed-resources: true
    toc: true
    toc-location: left
    grid:
      margin-width: 350px
####    mainfont: "Hiragino Maru Gothic Pro W4"
  docx: default
theme: 
  light: ../../addtosky.scss
  dark: darkly
lightbox: auto
title-block-banner: "#f0f3f5"
title-block-banner-color: "black"
callout-appearance: simple
callout-icon: false
bibliography: ../../seiro.bib
link-citations: true
reference-location: margin
citation-location: margin
---
```{css CSS setting, echo=FALSE, results = "hide"}
Blue {
  color: blue;
}
Red {
  color: red;
}
Purple {
  color: purple;
}
Gray {
  color: gray;
}
DarkBlue {
  color: #11017c;
}
```

<style type="text/css">
  body, td{
  font-size: 16pt;
}
</style>

<!-- LaTeX math shortcode -->
{{< include ../../MathShorthandUsingNewcommand.qmd >}}


# 「産業革命の技術進歩を促した要因」とは

イギリスで産業革命が起こったことは誰もが知っています。それまで農業に多かった就労者数が工業で増え始め、ついには逆転し、工業生産が飛躍的に増えました。

今までの研究でも、この過程を支えた技術進歩の要因がいくつか議論されていました。若干乱暴ですが簡単にまとめると、労働需要(企業)側の視点と労働供給(働く人)側の視点に大別できます。労働需要側の視点からは、賃金高騰とエネルギー(石炭)価格低下によって生産の機械化が進んだと主張されます。特定の生産要素(未熟練労働)がより希少=より高価になり、生産技術がそれに対応したという考えです[@Hicks1932; @Habakkuk1962; @Acemoglu2007; @Allen2009a]。

一方、労働供給側の視点からは、機械に習熟し技能および進歩観を持つ人(技術者)たちが生産過程に機械を取り入れる触媒となった、と主張されます[@Mokyr2009]。機械の発明はあったものの、実用化するにはさまざまな調整が必要で、技術者の集積なしに機械化は難しいためです。先行研究では後者を確認する実証研究が少数あります[@SquicciariniVoigtlander2015; @KellyMokyrOGrada2023]。

産業革命の技術進歩を促したのは労働需要側か、労働供給側か。どきどきする問いですが、今回紹介する研究の著者たちの答えは、「両方」でした。注意深く読むと労働需要側と労働供給側の議論が相互に排他的ではないことに気づきます。賃金が上昇してエネルギーが安くなったから機械で労働を代替した、その傾向は技術者が多い地域ほど強かった、と主張することも可能です。

今回の論文の素晴らしさは、対抗仮説と見なされていた両者を矛盾なく総合したこと、とくに、労働需要側の視点を厳密に実証した点にあります。労働供給側についても実証していますが、厳密さは若干劣ります。なお、後で見るように、本論文が検討しているのは農業機械化の進展なので、論文にあるように「産業革命の技術進歩を促した要因」ではなく「産業革命の農業技術進歩を促した要因」と記す方が正確です。産業革命本丸の工業ではなく、就労人口が減りつつあった農業での技術進歩です。読後にこのことを知って筆者は少し肩透かしを食った気になりました。

# 実証方法

この研究にはいくつかの目を見張る点があります。一つはナポレオン戦争に注目した実証方法です。賃金高騰する理由で当時最たるものは徴兵です。ナポレオン戦争は22年間の長さにわたり、イングランドとウェールズ全体で多くの男性が生産現場から去りました。この間、海軍は1.5万人規模から15万人規模まで増兵しています。一朝一夕というには長すぎる期間なので、生産現場では機械化がどうしても必要でした。

賃金高騰が激しい地域とは、海軍の動員が多かった地域のはずです。しかし、海軍が動員していたのは人口の多い地域だったので、海軍の動員に関係なく、機械化が進みやすい先進地域でもありました。このため、海軍動員数を機械化の要因として単純に示すと、海軍動員の生産機械化効果を過大に示すことになります。

そこで著者たちが注目したのが港の水深です。海軍船隻のような大型船は水深15メートル程度の深い港が必要です。一方、商業船隻はその半分程度の水深でも停泊可能でした。予想通り、各地域の海軍動員数は深い港からの距離によって説明可能でした。つまり、深い港に近い地域ほど海軍動員数が多かったのです。浅い港からの距離には、そのような関係はありませんでした。

深い港からの距離を媒介にして海外動員数を考え、その動員数が機械化を説明する、という2段階を踏んだ実証方法を著者たちはとりました。この方法を計量経済学では2段階最小自乗法(2SLS)といいます。この方法であれば、先進地域で賃金高騰によって機械化が進みやすくても、深い港から遠ければ海軍動員が進まないので、深い港からの距離&rArr;賃金高騰&rArr;機械化、という実証作業ループから外れます。


# データ

二つ目はデータです。海軍動員の時期と出身地を得るために、海軍史資料から船員名簿を収集、デジタル化しています。機械のデータは1750-1830年の地方新聞60紙で農家売却の全広告から農業機械部分を採集し^[抽出は大英博物館のデータベース検索に過ぎませんが、抜き出した広告を読んで重複や対象外を排除しています。さらに、1793-1815年の農業サーベイを使って農家の機械使用情報を補っています。 ] 、労働節約的機械と労働非節約的機械の数を得ました。^[労働節約的機械とは脱穀機、馬引き回転式熊手、馬鍬、農業用ローラー、籾すり機、労働非節約的機械とはチャフカッター、蕪切断機、クラッシャーすりこぎ機です。 ] 技術者数は網羅的な情報がないので、機械の特許データや徒弟年鑑などから地域の技術者指数を作成しています。^[分析は各地の技術者数が必要なので、すべての変数を地図上に描く作業をしています。1710-1791年(本文1792-1811年)に機械工徒弟過程を修了した63446人のうち地域が判明した`r 5308+568`人、Woodcroft(1854)が収集した1700-1790年(本文1792-1820年)の機械特許申請者リストから住所を抽出し、1792-1820年の新聞各紙の機械に関する知識や機械の利用に関する単語数から、共通する因子を統計学的に抜き出して(主要因分析の第一因子を)利用しています。 ] 賃金は農業サーベイ2万ページから抜粋、船隻移動には保険会社ロイズの記録をデジタル化、さらには、1841-1872年での王立農業学会主催の競技会での機械性能データ(「英国農業学会誌」所載)を使っています。もちろん、地図や海底地図も用いています。

# 結果

著者たちは、深い港に近い地域ほど海軍動員が多く賃金が高騰したこと、そうした地域では他地域よりも機械化が進んだことを示しました。これが労働需要側の実証です。

さらには、技術者指数が高いほど海軍動員による機械化の効果が高い、つまり、相乗効果があることも示しました。これが労働供給側の実証です。ただし、技術者数が多いのは先進地域でもあるため、相乗効果をもたらしたのが技術者数なのか、別の先進性要素なのかはっきりしません。別の先進性要素の効果を含む可能性があるため、労働供給側要因の実証は労働需要側と比べて厳密性で劣ります。

# 途上国への教訓

時代が異なる現代の途上国が得られる教訓は、市場ベースでは要素賦存に準じた技術が採用される、ということでしょう。そして、技術者が多いほど生産現場への導入は進みます。当時の技術は単純で、機械を扱う労働者の識字は不要だったと思いますが、現代では機械などの取り扱いに識字と計算の能力は必須です。基礎的な学力を持つ国民に加えて技術者を供給できれば、それに準じた技術の普及が見込めそうです。その際に政府が「成長分野」の技術を選定し補助金を支出したりすると、要素賦存に応じた技術を選ぶ企業にとっては余計なノイズになります。AIなどデジタル分野での技術革新が顕著でも、自国にエンジニアが少なければデジタル技術の採用は進みません。政府はあくまでも学習機会提供と技術者育成に自らの役割を限定し、企業に自由に技術を選ばせることが大事かもしれません。

