---
title: |
  イギリスの経済成長が始まったのは1600年前後\
subtitle: "Paul Boucasse, Emi Nakamura, Jon Steinsson"
author: "成朗"
date: last-modified
date-format: "MMMM DD, YYYY, HH:MM ZZ"
execute:
  echo: false
  freeze: auto  # re-render only when source changes
engine: knitr
pdf-engine: lualatex
format:
  html:
    standalone: true
    embed-resources: true
    toc: true
    toc-location: left
    grid:
      margin-width: 350px
    linkcolor: "green"
    urlcolor: "#009900"
#### this does not work
####    include-in-header: ../MathShorthand.html 
####  pdf: default
  docx: default
  epub: default
lightbox: auto
theme: sky
  ####light: [sky, ./sky-add]
  ####dark: darkly
backgroundcolor: "#fffcf2"
title-block-banner: "#f0f3f5"
title-block-banner-color: "black"
doi-title: "doi.org/10.1086/734780"
callout-appearance: simple
callout-icon: false
bibliography: ../../seiro.bib
link-citations: true
reference-location: margin
citation-location: margin
#### # quarto render DelabastitaRubens.qmd
#### c:\seiro\languages\R\R-4.4.1\bin\x64\Rscript.exe -e "path <- 'c:/seiro/docs/personal/Miscelleneous/QuartoFiles/posts/DelabastitaRubens/'; rmarkdown::render(paste0(path, 'DelabastitaRubens.Rmd'), output_format = 'all')"
---
```{css CSS setting, echo=FALSE, results = "hide"}
/* Define a margin before hX (header level X) element */
h1  {
  margin-top: 3ex;
  margin-bottom: 3ex;
  /* background: #c2edff; */ /*背景色*/
  padding: 0.5em;/*文字まわり（上下左右）の余白*/
}
h2  {
  margin-top: 2ex;
  margin-bottom: 2ex;
  padding: 0.5em;/*文字周りの余白*/
  ####color: #010101;/*文字色*/
  color: #87a5f2;
  /* background: #eaf3ff; */ /*背景色*/
  /* border-bottom: solid 3px #516ab6; */ /*下線*/
}
DBlue {
  color: dodgerblue;
}
Blue {
  color: blue;
}
Red {
  color: red;
}
```

<style type="text/css">
  body, td{
  font-size: 16pt;
}
</style>


::: {.flushright}

[doi.org/10.1093/qje/qjae046](https://doi.org/10.1093/qje/qjae046)

:::


# 産業革命の遙か前から成長していた

成長開始当初を統治したエリザベス女王が現在のわれわれの生活を聞いたら、SFか、と思うでしょう。無理もありません。暑いときには冷房の効いた部屋にいながら好きなものが配達されます。お休みが長期あり、そのお休みには空を飛んで外国に行き、雲を見下ろして食事をしながら宿泊先を予約できます。病気で死ぬ心配が減り、100歳まで生きる人が続出します。遠方の誰かから文章や音声で連絡が来ると、機械の秘書がスケジュール帳を見て返答の選択肢を話しかけるので、「2番目、この前と違う程々の値段のお土産を買って」と話すと、丁寧な返事をして相手が好きそうな名産品を程々の値段で注文し、アポ内容を記録してくれます。

こうした現実は経済成長をなしえたからこそ、享受できます。

では、経済成長、つまり、一人あたり所得の成長はなぜ可能になったのでしょうか。その問いに答えるためには、経済成長の開始時期を知る必要があります。経済成長が始まった時期を問われると、イギリスの産業革命(1800年前後)から、と多くの人は考えるかもしれません。しかし、1980年代頃からこうした見方は修正されるようになり、現在は遅くとも18世紀半ばには生産量が増えていたと主張されています。

今回紹介する研究は、驚くべきことに、さらに150年前まで開始時期が遡ると主張しています。彼らの研究では、イギリスでは1600年前後(産業革命の200年前)から成長が始まっていたことを示しています。19世紀の急速な経済成長の前に、200年もの成長期間があったのです。

# 研究デザイン

この研究の面白さはいろいろありますが、変わったところとして論文の著者たちがハードコアの経済史家ではないことが挙げられます。著者たちは資料を発掘しデータを作り上げる経済史家ではなく、マクロ経済学の専門家です。このため、この研究では他の経済史家が作成した資料を借用しています。主たる資料は実質賃金[@Clark2010 作成]と人口[@Clark2007b; @WrigleyEtAl1997 作成]で、いずれも1250-1850年の10年ごとの平均値です。既存資料を使いつつ新たな知見を示せたのは、異なる手法を用いたためです。

働き手が増えると賃金は低下します(労働需要曲線が右下がりだからです)。労働量の多寡に応じて決まる賃金水準は、労働が生産量に転化する比率(弾力性、正確には労働量1%増加したときの生産量変化率、完全競争労働市場では賃金の変化率に等しい)や生産性(TFP)が高いほど高くなります。違う言い方をすれば、弾力性の値さえ分かれば、労働(=人口)と賃金のデータから生産性を逆算できるのです。^[土地$Z$、労働$L_{t}$、生産性$A_{t}$のコブダグラス型生産関数$Y_{t}=A_{t}Z^{\alpha}L^{1-\alpha}_{t}$で利潤最大化の一階条件を対数(小文字)表示すると
$$w_{t}=\phi+a_{t}-\alpha l_{t}$$
です。ここで$\phi = \ln(1 - \alpha) + \alpha \ln Z$と表記しています。もしも、弾力性$\alpha$が分かると、各時点の賃金、労働、土地(=不変と仮定)のデータで(対数)生産性$a_{t}$を計算できます。
$$\hat{a}_{t}=w_{t}-\hat{\phi}+\hat{\alpha} l_{t}$$
 ]
これはマクロ経済学の教科書的な手法です。

弾力性の値を得るために、著者たちは黒死病により人口が急減した時期(1348-1366)に着目しました。そしてデータから1340年-1360年の賃金増加率と人口減少率の比を計算し、弾力性の値(0.7)を得ました。著者たちは黒死病という自然実験に着目することで弾力性を計算でき、それゆえに生産性を逆算できたのです。

計算した生産性を図に描くと、生産性は1600年頃から微増し、1810年以降は急激に増えていました。著者たちはモデルを拡張して、現実性を高めた設定でも結果が変わらないことを確認しています。たとえば、資本を生産関数に含めた場合、実質所得が増えることで人口が増えるマルサス的な人口動態を考慮した場合、などです。

# ベイジアン推計

データは10年平均値なので観測できるのは61回だけ(T=61)です。生産性のように長期的に上昇傾向のあるデータは非定常的かもしれません。通常は(標本学派では)非定常性の検定をして、定常・非定常ごとに異なる分析をしますが、61だと非定常性検定のための観測数が十分とはいえません。一方、ベイジアン推計には定常・非定常の区別はなく、すべてに共通の分析ができます。^[この点は筆者の同僚の橋口善弘さんの指摘によります。時間とともに変化する弾力性を推計するカルマン・フィルターも定常データにのみ適用され、かつ、線形性を仮定する必要があります。 ]こうした利点からか、著者たちはベイジアン推計を採用しています。 ^[一方、小標本なので事前分布の影響を受けやすいことを念頭に置く必要があります。 ] 著者たちはデータの測定誤差に配慮し、その影響をベイジアン推計に巧みに取り込んでいます。

# 成長のきっかけは何か

1600年前後というタイミングを確定させることは何でもないように思えますが、学術的には大きな影響力があります。成長の契機として主張されてきた各学説のうち、1600年よりも大幅に遅い出来事は却下されるためです。最たる例が名誉革命(1688年)です。これ以降、議会によって王権は制限され、徴税が乱発されず私的所有権が保障され、囲い込み(エンクロージャ)にも発展しました。1600年前後という時期特定は @NorthWeingast1989 や @BogartRichardson2011 らの名誉革命&rarr;産業革命とする見解と矛盾するとまでいえませんが、第二義的な影響しかなかったといえそうです。

1600年前後と整合的な学説は、農業の生産性上昇と農業就労人口低下[@WallisColsonChilosi2018]、ヘンリー8世の教会領没収[@HeldringRobinsonVollmer2021]、ヨーマンの興隆[@Allen1992]、貿易・植民地とロンドン都市化[]、活版印刷と識字率上昇[@Dittmar2011]などです。一方、進歩主義思想・ブルジョワ的価値[@Mokyr2009; @Mokyr2016;  @McCloskey2006]やプロテスタンティズムの倫理[@Weber1904; @Tawney1926]などは整合的であるがタイミングを示しづらい、と著者たちは述べています。

# エネルギー革命の証拠

産業革命といえば、蒸気機関+紡績機械=大量生産、というイメージがあるかもしれません。これを可能にしたのは、生産で用いる動力源を森林、役畜、人間などから石炭に代替させたエネルギー革命です。これを生産過程の入力・出力として表現すると、生産における土地の重要性低下と言い換えられます。森林、役畜、人間が動力を提供するためには、森林が土地を要するだけでなく、飼料、食料のために耕作地が欠かせません。石炭が動力源の主力になり工場生産が増えると、生産額一単位あたりに土地を以前ほど使わなくなります。つまり、容易に増やすことのできない土地の制約から経済を解放し、生産を(工場内で)増やせるようになったのです。これに応じて、年間労働日数も成長開始前の約150日から1800年代以降は2倍以上に延びています。

土地をあまり使わなくなると、土地の入力量の変化に対し生産量が反応しなくなります。つまり、生産の土地弾力性が下がります。著者たちは、労働、資本、土地の3要素を用いる生産関数を推計し、この解釈通りに産業革命以降に土地の弾力性が半減したことを示しました。それと対応して、資本と労働の弾力性が高まっていました。成長開始期の特定と直接の関係はないですが、エネルギー革命の証拠を生産関数を用いて示したのは画期的といえます。

# マルサス的モデルの有効性

本研究はマルサス的な人口動態を考慮した理論モデルの枠組みにデータを流し込むことで、成長開始とその後の加速を示しています。これはマルサス的モデルの有効性を示すことにもなっています。第一に、マルサス的な貧困の罠に瀕しながら蒸気機関登場前のイギリスで成長が開始したことは、(古代ギリシャ、古代ローマ、宋代中国、イスラム黄金期など)古代から中世における持続的経済成長期(efforescence)もマルサス的な貧困の罠と矛盾しないことを示しました。第二に、18世紀に発生した生産拡大の中の賃金停滞(Engels' Pause)は、マルサス的な人口増大によって引き起こしたものであり、エンゲルスが主張したような資本家による搾取、つまり、労働分配率(コブ・ダグラス型生産関数での労働弾力性)の低下が原因ではないことを示しました。

# 途上国への示唆

成長の開始時期を今まで考えられていたよりも昔の年代に特定したことだけでは、何が成長を引き起こしたか分かりません。よって、このこと自体に現代の途上国への示唆はないように思えます。自然に成熟して産業革命に到達したイギリスはそのまま成長を続けましたが、ベルギーやドイツのように、政府が主導して意識的に産業革命に到達した後発国の経験を途上国は学ぶべきかもしれません。むろん、国際競争環境は当時と現代では大きく異なります。石炭供給と鉄鋼生産(ベルギーの例は本コラム「共謀したのは労働者の搾取」でも紹介)などを現代風に置き換える必要があるでしょう。そして、「東アジアの奇跡」を踏まえて、バングラデシュ、エチオピア、モーリシャスなどの輸出志向的製造業が牽引役となった成長戦略も参考になります。

一定の教育水準を備えた労働力の供給、技術と資本の(国外からの)誘致、インフラと生産に関わる諸制度の整備など、イギリスが時間をかけて得たものを圧縮して準備するのは大変です。しかし、70年以上の時間をかけて地道に就学率を高め、制度を整備してきた結果、イギリス成長の開始から4世紀と四半世紀を経て、一昔前の最貧国でも成長が始まっています。


<!--
イギリスでも国際貿易は産業革命後の成長にとって必須でした。アメリカなどの市場規模大国を除き、現在までの各国の経済成長でも同様です。東アジアだけでなく、バングラデシュでも、エチオピアでも、モーリシャスでも、輸出志向的な産業が成長をもたらしました。
-->


