# Workflow for rendering and deploying quarto site to GitHub Pages
# Based on the GitHub example static content deploy action
name: Deploy Quarto site to Pages

on:
  # Run CI (continuous integration) when a PR targets main (this is what you want for branch protection)
  pull_request:
    branches: ["main"]
  # Run CI + deploy when code is pushed to main
  push:
    branches: ["main"]
  # Allow manual run from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
# Permissions:
# - For PR builds, only read permissions are needed.
# - For deployments to Pages, pages + id-token are needed.
#   (GitHub is fine with having these set globally.)
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  render-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: SPECIFIC-QUARTO-VERSION-HERE

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.1'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            any::knitr
            any::rmarkdown
            any::kableExtra
            any::ggplot2
            any::data.table
            any::tufte
            any::modelsummary
            any::treemap
            any::ggfittext
            any::RefManageR
            any::ggrepel

      # Render the site
      # This will fail the workflow if rendering fails,
      # which is exactly what you want for CI.
      - name: Render
        uses: quarto-dev/quarto-actions/render@v2

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          # path: 'posts' ==> Github Pages: root = posts/
          # path: '.'     ==> Github Pages: root = repo root, posts/ stays in URL
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
          (github.event_name == 'pull_request' && startsWith(github.head_ref, 'dependabot/'))
        uses: actions/deploy-pages@v5
